#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run prettier to format files and fail if there are any formatting issues
npx prettier --write --check "src/**/*.{ts,tsx}" "*.{ts,tsx}"

# Run linting
npm run lint

# Add the formatted files back to staging
git add .
